---
title: "Current Research project"
output:
  html_document:
    toc: False
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

### DONUTS (2025 - 2029)

**Design and Modeling of Multi-Scale and Multi-Technology Future Networks: From 5G/6G Cellular to Non-Terrestrial Networks**

This project is part of the PEPR on Futur Networks and aims to design a space-air-ground continuum to ensure seamless connectivity and deterministic latency in mobile networks. It requires optimizing network functions and resources in response to dynamic conditions, including infrastructure mobility. A multi-scale digital twin will assess the impact of adaptation strategies, calibrated using real-world measurements and analytical models. As a member of the project, I'm focusing on how multipath connectivity, both at the edge (RAN) and within the core network, can be leveraged to meet stringent KPIs and to provide guaranteed performance metrics. The project budget is €2.4M for a duration of 56 months.

More information on the [project web page](https://donuts-project.space)

<br>

### TURFU-NET (2024 - 2028)

**Transcending the Usual Rationale for the Future of Ubiquitous NETworks**

TURFU-NET is a collaborative research project involving public entities at the national level, funded by the French National Research Agency (ANR 🇫🇷) under the 2024 call for proposals on Specific Topics in Artificial Intelligence (TSIA), with a focus on Artificial Intelligence for Future Networks. As a member of the project, I am primarily involved in developing innovative data collection schemes and detecting gray failures using AI. The project has been awarded €577k in funding for a duration of 48 months.

More information on the [project web page](https://turfu.icube.unistra.fr)

<br>

### PERENNE (2024 - 2028)

**Programmable wireless communication stack for sustainable deployments**

Perenne is a collaborative research project between public entities at national level (PRC) funded by the French National Agency (ANR🇫🇷) in the 2023 generic call for proposals (AAPG) by the scientific evaluation panel (CES) 25. Perenne is certified by the competitive cluster Images & Réseaux. I'm the scientific coordinator of the project. The project has been granted a funding amount of k€632 over a period of 48 months.

More information on the [project web page](https://perenne.icube.unistra.fr)

<br>

### PEPR Future Networks - MUST Project (2023 - 2029)

**End-to-End multi-domain services management architecture of the networks of the future**

This project is part of the PEPR on Futur Networks and focuses on managing diverse services across various sectors using a scalable infrastructure fit for future 5G/6G networks. It emphasizes secure distributed services and coordinating interactions among stakeholders. MUST ensures aligning service requests with network capacities throughout their lifecycle. In this project, I serve as the Principal Investigator representing the ICube lab. The project has been granted a funding amount of €3.7 million over a period of six years.

More information on the [project web page](https://pepr-futurenetworks.fr/en/projet/must/)