---
title: ""
output:
  html_document:
    toc: False
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Publications {.tabset .tabset-fade .tabset-pills}

## Sort by year

### 2022

- [**Mobility Support in Low Power Asynchronous Wireless Networks**](http://clarinet.icube.unistra.fr/~montavont/hdr-montavont.pdf), J. Montavont, ***HDR Thesis***, University of Strasbourg, FRANCE, November 2022
- [**Towards a Fully Programmable Internet of Things**](https://doi.org/10.1109/WiMob55322.2022.9941617), A. Bruniaux, J. Montavont, T. Noël, G. Papadopoulos and N. Montavont, in proceedings of the ***IEEE International Conference on Wireless and Mobile Computing, Networking and Communications (WiMob)***, Thessaloniki, Greece, October 2022
- [**SDN-TSCH: Enabling Software Defined Networking for Scheduled Wireless Networks with Traffic Isolation**](https://doi.org/10.1109/ISCC55528.2022.9913024), F. Veysi, J. Montavont and F. Théoleyre, in proceedings of the ***IEEE Symposium on Computers and Communications (ISCC)***, Rhodes Island, Greece, June 2022
- [**The revenge of asynchronous protocols: Wake-up Radio-based Multi-hop Multi-channel MAC protocol for WSN**](https://doi.org/10.1109/WCNC51071.2022.9771641), N. El Hoda Djidi, S. Sampayo, J. Montavont, A. Courtay, M. Gautier, O. Berder and T. Noël, in proceedings of the ***IEEE Wireless Communications and Networking Conference (WCNC)***, Austin, TX, USA, April 2022

### 2021

- [**REFLOOD: Reactive Routing Protocol for Wake-Up Radio in IoT**](https://doi.org/10.1016/j.adhoc.2021.102578), S. Sampayo, J. Montavont and T. Noël, in ***Elsevier Ad Hoc Networks***, Volume 121, October 2021 

### 2020

- [**A Performance Study of the Behavior of the Wake-Up Radio in Real-World Noisy Environments**](https://www.ewsn.org/file-repository/ewsn2020/206_211_sampayo.pdf), S. Sampayo, J. Montavont and T. Noël, in proceedings of the ***Workshop on Wake-Up radio technologies for next generation wireless communications (AWAKE), in conjunction with EWSN***, Lyon France, February 2020 

### 2019

- [**eLoBaPS: Towards Energy Load Balancing with Wake-Up Radios for IoT**](https://doi.org/10.1007/978-3-030-31831-4_27), S. Sampayo, J. Montavont and T. Noël, in proceedings of the ***International Conference on Ad-Hoc Networks and Wireless (AdHoc-Now)***, Luxembourg, October 2019
- [**Sharing is Caring a Cooperation Scheme for RPL Network Resilience and Efficiency**](https://doi.org/10.1109/ISCC47284.2019.8969588), B. Foubert and J. Montavont, in proceedings of the ***IEEE International Symposium on Computer Communications (ISCC)***, Barcelona Spain, July 2019
- [**LoBaPS: Load Balancing Parent Selection for RPL Using Wake-Up Radios**](https://doi.org/10.1109/ISCC47284.2019.8969748), S. Sampayo, J. Montavont and T. Noël, in proceedings of the ***IEEE International Symposium on Computer Communications (ISCC)***, Barcelona Spain, July 2019
- [**Selecting Parents with Wake-Up Radios for Load Balancing in RPL**](https://hal.archives-ouvertes.fr/hal-02124314), S. Sampayo, J. Montavont et T. Noël, dans les actes du ***colloque francophone sur la conception de protocoles, l’évaluation de performance et l’expérimentation des réseaux de communication (CoRes)***, Saint Laurent de la Cabrerisse, France, Juin 2019

### 2018

- [**Is Wake-Up Radio the Ultimate Solution to the Latency-Energy Tradeoff in Multi-hop Wireless Sensor Networks?**](https://doi.org/10.1109/WiMOB.2018.8589163) S. Sampayo, J. Montavont, F. Pregaldiny and T. Noël, in proceedings of the ***IEEE International Conference on Wireless and Mobile Computing, Networking and Communications (WiMob)***, Limassol Cyprus, October 2018 (acceptance rate: 28%)

### 2016

- [**MT-RPL: a cross-layer approach for mobility support in RPL**](http://dx.doi.org/10.4108/eai.1-12-2016.151712), C. Cobârzan, J. Montavont and T. Noël, in ***EAI Endorsed Transactions on Internet of Things***, Volume 2, Issue 5, December 2016
- [**Indoor Deployment of Low-Power Wide Area Networks (LPWAN): a LoRaWAN case study**](http://dx.doi.org/10.1109/WiMOB.2016.7763213), P. Neumann, J. Montavont and T. Noël, in proceedings of the ***IEEE International Conference on Wireless and Mobile Computing, Networking and Communications (WiMob)***, New York USA, October 2016 (acceptance rate: 26.8%)
- [**RPL Border Router Redundancy in the Internet of Things**](http://dx.doi.org/10.1007/978-3-319-40509-4_14), Q-D. Nguyen, J. Montavont, N. Montavont and T. Noël, in proceedings of the ***International Conference on Ad-Hoc Networks and Wireless (AdHoc-Now)***, Lille France, July 2016 (acceptance rate: 37%)

### 2015

- [**Integrating Mobility in RPL**](http://dx.doi.org/10.1007/978-3-319-15582-1_9), C. Cobarzan, J. Montavont and T. Noël, in proceedings of the ***European Conference on Wireless Sensor Networks (EWSN)***, Porto Portugal, February 2015 (acceptance rate: 21.5%)
- [**Theoretical Analysis of IPv6 Stateless Address Autoconfiguration in Low-power and Lossy Wireless Networks**](http://dx.doi.org/10.1109/RIVF.2015.7049899), J. Montavont, C. Cobarzan and T. Noël, in proceedings of the ***IEEE RIVF International Conference on Computing and Communication Technologies (RIVF)***, Cantho Vietnam, January 2015 (acceptance rate: 42%)

### 2014

- [**Analysis and Performance Evaluation of RPL under Mobility**](http://dx.doi.org/10.1109/ISCC.2014.6912471), C. Cobarzan, J. Montavont and T. Noël, in proceedings of the ***IEEE Symposium on Computers and Communications (ISCC)***, Madeira Portugal, June 2014 (acceptance rate: 46.4%)
- [**Mobile IPv6 in Internet of Things: Analysis, Experimentations and Optimizations**](http://dx.doi.org/10.1016/j.adhoc.2013.11.001), J. Montavont, D. Roth and T. Noël, in ***Elsevier Ad Hoc Networks***, Volume 14, pp. 15-25, March 2014 (IF: 1.66)
- [**Thorough Empirical Analysis of X-MAC over a Large Scale Internet of Things Testbed**](http://dx.doi.org/10.1109/JSEN.2013.2281910), J. Baudeaux, A. Gallais, J. Montavont, T. Noël, D. Roth and E. Valentin, in ***IEEE Sensors Journal, Special Issue on Internet of Things (IoT): Architecture, Protocols and Services***, Volume 14, Issue 2, pp. 383-392, February 2014 (IF: 1.889)

### 2013

- [**Improving the Medium Access in Highly Mobile Wireless Sensor Networks**](http://dx.doi.org/10.1007/s11235-011-9565-6), R. Kuntz, J. Montavont and T. Noël, in ***Springer Journal of Telecommunication System, Special Issue on Recent Advance in Mobile Sensor Networks***, Volume 52, Issue 4, pp. 2437-2458, April 2013 (IF: 0.822)
- [**Multihoming in IPv6 Mobile Networks: Progress, Challenge and Solutions**](http://dx.doi.org/10.1109/MCOM.2013.6400449), R. Kuntz, J. Montavont and T. Noël, in ***IEEE Communication Magazine***, Volume 51, Issue 1, pp. 128-135, January 2013 (IF: 5.125)

### 2012

- [**Performance Evaluation of Mobile IPv6 Over 6LoWPAN**](http://dx.doi.org/10.1145/2387027.2387041), D. Roth, J. Montavont and T. Noël, in proceedings of the ***ACM International Symposium on Performance Evaluation of Wireless Ad Hoc, Sensor, and Ubiquitous Networks (PEWASUN)***, Paphos Cyprus Island, October 2012 (aceptance rate: 17%)
- **De l'Internet mobile à la mobilité dans l'Internet des objets**, J. Montavont, A. Gallais et T. Noël, Article invité dans les actes des ***journées francophones Mobilité et Ubiquité (Ubimob)***, Anglet France, June 2012 

### 2011

- [**An Improved Network Mobility Service for Intelligent Transportation Systems**](http://dx.doi.org/10.1002/wcm.860), R. Kuntz, J. Montavont, G. Schreiner, D. Binet, and T. Noël, in *Wiley InterScience Wireless Communications and Mobile Computing*, Volume 11, Issue 7, pp. 899-915, July 2011 (IF: 0.922)
- [**Overhearing for Congestion Avoidance in Wireless Sensor Networks**](http://dx.doi.org/10.1007/978-3-642-22450-8_10), D. Roth, J. Montavont and T. Noël, in proceedings of the ***International Conference on Ad Hoc and Wireless (ADHOC-NOW)***, Paderborn Germany, July 2011 (acceptance rate 42%)
- [**LIFT: Layer Independent Fault Tolerance Mechanism for Wireless Sensor Networks**](http://dx.doi.org/10.1109/VETECS.2011.5956762), J. Beaudaux, A. Gallais, J. Montavont and T. Noël, in proceedings of the IEEE ***Vehicular Technology Conference (VTC-Spring)***, Budapest Hungary, May 2011 (acceptance rate 51%)
- [**MOBINET: Mobility Management Across Different Wireless Sensor Networks**](http://dx.doi.org/10.1109/WCNC.2011.5779156), D. Roth, J. Montavont and T. Noël, in proceedings of the ***IEEE Wireless Communications and Networking Conference (WCNC)***, Cancun Mexico, March 2011 (acceptance rate: 48%) 

### 2010

- [**CASINO: Creating Alea with a Sensor-based Interactive Network**](http://dx.doi.org/10.1145/1869983.1870033), J. Beaudaux, A. Gallais, R. Kuntz, J. Montavont, T. Noël, D. Roth, F. Théoleyre and E. Valentin, demonstration abstract in proceedings of the ***ACM Conference on Embedded Networked Sensor Systems (SenSys)***, Zurich Switzerland, November 2010
- [**MOBINET : Gestion de la Mobilité à travers différents Réseaux de Capteurs Sans Fil**](http://hal.inria.fr/inria-00475581), D. Roth, J. Montavont and T. Noël, dans les actes des ***Rencontres Francophones sur les Aspects Algorithmiques de Télécommunications (Algotel)***, Côte d'Opale France, June 2010 (acceptance rate 57%)

### 2008

- [**Implementation of an IPv6 Stack for NS-3**](http://dx.doi.org/10.4108/ICST.VALUETOOLS2008.4374), S. Vincent, J. Montavont, N. Montavont, in proceedings of the ***International Workshop on NS-2 (WNS2), in conjunction with the International Conference on Performance Evaluation Methodologies and Tools (VALUETOOLS)***, Athens Greece, October 2008
- [**Multiple Mobile Routers in NEMO: How Neighbor Discovery Can Assist Default Router Selection**](http://dx.doi.org/10.1109/PIMRC.2008.4699613), R. Kuntz, J. Montavont, T. Noël, in proceedings of the ***IEEE International Symposium on Personal Indoor and Mobile Radio Communications (PIMRC)***, Cannes France, September 2008
- [**Thorough Empirical Analysis of the IETF FMIPv6 Protocol over IEEE 802.11 Networks**](http://dx.doi.org/10.1109/MWC.2008.4492979), E. Ivov, J. Montavont and T. Noël, in ***IEEE Wireless Communications Magazine, special issue on Architectures and Protocols for Mobility Management in All-IP Mobile Networks***, Volume 15, Issue 2, pp. 65-72, April 2008 (IF: 4.148)
- [**Advantages of Flow Bindings: an Embedded Mobile Network Use Case**](http://dl.acm.org/citation.cfm?id=1390576.1390593), A. Boutet, B. Le Texier, J. Montavont, N. Montavont and G. Schreiner, in proceedings of the ***Workshop on Experimental Evaluation and Deployment Experiences on Vehicular Networks (WEEDEV), in conjunction with TRIDENTCOM***, Innsbruck Austria, March 2008

### 2007

- [**Analysis of a Geolocation-based FMIPv6 Extension for Next Generation Wireless LANs**](http://ubicc.org/files/pdf/UBICC-montavont_101_101.pdf), J. Montavont, E. Ivov, T. Noël and K. Guillouard, in ***Ubiquitous Computing and Communication Journal***, Volume 2, Number 5, October 2007
- [**Analysis of Mobile IPv6 Handover Optimizations and their Impact on Real-Time Communication**](http://dx.doi.org/10.1109/WCNC.2007.598), J. Montavont, E. Ivov and T. Noël, in proceedings of the ***IEEE Wireless Communications and Networking Conference (WCNC)***, Hong Kong China, March 2007 (acceptance rate: 47%)
- [**Wireless IPv6 Simulator: SimulX**](http://dl.acm.org/citation.cfm?id=1404595.1404634), N. Montavont, J. Montavont and S. Hachana, in proceedings of the ***ACM/SIGSIM Communications and Networking Simulation Symposium (CNS), located with Spring Simulation Multiconference 2007 (SpringSim)***, Norfolk USA, March 2007

### 2006

- [**Gestion des déplacements de terminaux IPv6 mobiles assistée par géolocalisation**](http://clarinet.icube.unistra.fr/~montavont/these-montavont.pdf), J. Montavont, ***PhD Thesis***, Louis Pasteur University, Strasbourg, FRANCE, December 2006
- [**Anticipation des Handovers des Nœuds IPv6 à l'aide d'information de Géolocalisation**](http://hal.inria.fr/inria-00110275), J. Montavont, T. Noël and K. Guillouard, dans les actes du ***Colloque Francophone sur l'Ingenierie des Protocoles (CFIP)***, Tozeur Tunisia, November 2006
- [**Deploying NEMO: A Practical Approach**](http://dx.doi.org/10.1109/ITST.2006.288768), J. Montavont, J. Lorchat and T. Noël, in proceedings of the ***International Conference on ITS Telecommunications (ITST)***, Chengdu China, June 2006
- [**IEEE 802.11 Handovers Assisted by GPS Information**](http://dx.doi.org/10.1109/WIMOB.2006.1696358), J. Montavont and T. Noël, in proceedings of the ***IEEE International Conference on Wireless and Mobile Computing, Networking and Communications (WiMob)***, Montréal Canada, June 2006

### 2005

- [**Enhanced schemes for L2 handover in IEEE 802.11 networks and their evaluations**](http://dx.doi.org/10.1109/PIMRC.2005.1651681), J. Montavont, N. Montavont and T. Noël, in proceedings of the ***IEEE International Symposium on Personal Indoor and Mobile Radio Communications (PIMRC)***, Berlin Germany, September 2005 

## Sort by type

### Thesis

- [**Mobility Support in Low Power Asynchronous Wireless Networks**](http://clarinet.icube.unistra.fr/~montavont/hdr-montavont.pdf), J. Montavont, ***HDR Thesis***, University of Strasbourg, FRANCE, November 2022
- [**Gestion des déplacements de terminaux IPv6 mobiles assistée par géolocalisation**](http://clarinet.icube.unistra.fr/~montavont/these-montavont.pdf), J. Montavont, ***PhD Thesis***, Louis Pasteur University, Strasbourg, FRANCE, December 2006

### Refereed International Journals (9)

- [**REFLOOD: Reactive Routing Protocol for Wake-Up Radio in IoT**](https://doi.org/10.1016/j.adhoc.2021.102578), S. Sampayo, J. Montavont and T. Noël, in ***Elsevier Ad Hoc Networks***, Volume 121, October 2021
- [**MT-RPL: a cross-layer approach for mobility support in RPL**](http://dx.doi.org/10.4108/eai.1-12-2016.151712), C. Cobârzan, J. Montavont and T. Noël, in ***EAI Endorsed Transactions on Internet of Things***, Volume 2, Issue 5, December 2016
- [**Mobile IPv6 in Internet of Things: Analysis, Experimentations and Optimizations**](http://dx.doi.org/10.1016/j.adhoc.2013.11.001), J. Montavont, D. Roth and T. Noël, in ***Elsevier Ad Hoc Networks***, Volume 14, pp. 15-25, March 2014 (IF: 1.66)
- [**Thorough Empirical Analysis of X-MAC over a Large Scale Internet of Things Testbed**](http://dx.doi.org/10.1109/JSEN.2013.2281910), J. Baudeaux, A. Gallais, J. Montavont, T. Noël, D. Roth and E. Valentin, in ***IEEE Sensors Journal***, Special Issue on Internet of Things (IoT): Architecture, Protocols and Services, Volume 14, Issue 2, pp. 383-392, February 2014 (IF: 1.889)
- [**Improving the Medium Access in Highly Mobile Wireless Sensor Networks**](http://dx.doi.org/10.1007/s11235-011-9565-6), R. Kuntz, J. Montavont and T. Noël, in ***Journal of Telecommunication System, special issue on Recent Advance in Mobile Sensor Networks***, Volume 52, Issue 4, pp. 2437-2458, Springer, April 2013 (IF: 0.822)
- [**Multihoming in IPv6 Mobile Networks: Progress, Challenge and Solutions**](http://dx.doi.org/10.1109/MCOM.2013.6400449), R. Kuntz, J. Montavont and T. Noël, in ***IEEE Communication Magazine***, Volume 51, Issue 1, pp. 128-135, January 2013 (IF: 5.125)
- [**An Improved Network Mobility Service for Intelligent Transportation Systems**](http://dx.doi.org/10.1002/wcm.860), R. Kuntz, J. Montavont, G. Schreiner, D. Binet and T. Noël, in ***Wiley InterScience Wireless Communications and Mobile Computing***, Volume 11, Issue 7, pp. 899-915, July 2011 (IF: 0.922)
- [**Thorough Empirical Analysis of the IETF FMIPv6 Protocol over IEEE 802.11 Networks**](http://dx.doi.org/10.1109/MWC.2008.4492979), E. Ivov, J. Montavont and T. Noël, in ***IEEE Wireless Communications Magazine, Special Issue on Architectures and Protocols for Mobility Management in All-IP Mobile Networks***, Volume 15, Issue 2, pp. 65-72, April 2008 (IF: 4.148)
- [**Analysis of a Geolocation-based FMIPv6 Extension for Next Generation Wireless LANs**](http://ubicc.org/files/pdf/UBICC-montavont_101_101.pdf), J. Montavont, E. Ivov, T. Noël and K. Guillouard in ***Ubiquitous Computing and Communication Journal***, Volume 2, Number 5, October 2007 

### Refereed International Conferences (22)

- [**Towards a Fully Programmable Internet of Things**](https://doi.org/10.1109/WiMob55322.2022.9941617), A. Bruniaux, J. Montavont, T. Noël, G. Papadopoulos and N. Montavont, in proceedings of the ***IEEE International Conference on Wireless and Mobile Computing, Networking and Communications (WiMob)***, Thessaloniki, Greece, October 2022
- [**SDN-TSCH: Enabling Software Defined Networking for Scheduled Wireless Networks with Traffic Isolation**](https://doi.org/10.1109/ISCC55528.2022.9913024), F. Veysi, J. Montavont and F. Théoleyre, in proceedings of the ***IEEE Symposium on Computers and Communications (ISCC)***, Rhodes Island, Greece, June 2022
- [**The revenge of asynchronous protocols: Wake-up Radio-based Multi-hop Multi-channel MAC protocol for WSN**](https://doi.org/10.1109/WCNC51071.2022.9771641), N. El Hoda Djidi, S. Sampayo, J. Montavont, A. Courtay, M. Gautier, O. Berder and T. Noël, in proceedings of the ***IEEE Wireless Communications and Networking Conference (WCNC)***, Austin, TX, USA, April 2022
- [**eLoBaPS: Towards Energy Load Balancing with Wake-Up Radios for IoT**](https://doi.org/10.1007/978-3-030-31831-4_27), S. Sampayo, J. Montavont and T. Noël, in proceedings of the ***International Conference on Ad-Hoc Networks and Wireless (AdHoc-Now)***, Luxembourg, October 2019
- [**Sharing is Caring a Cooperation Scheme for RPL Network Resilience and Efficiency**](https://doi.org/10.1109/ISCC47284.2019.8969588), B. Foubert and J. Montavont, in proceedings of the ***IEEE International Symposium on Computers and Communications (ISCC)***, Barcelona Spain, June 2019
- [**LoBaPS: Load Balancing Parent Selection for RPL Using Wake-Up Radios**](https://doi.org/10.1109/ISCC47284.2019.8969748), S. Sampayo, J. Montavont and T. Noël, in proceedings of the ***IEEE International Symposium on Computers and Communications (ISCC)***, Barcelona Spain, June 2019
- [**Is Wake-Up Radio the Ultimate Solution to the Latency-Energy Tradeoff in Multi-hop Wireless Sensor Networks?**](https://doi.org/10.1109/WiMOB.2018.8589163), S. Sampayo, J. Montavont, F. Pregaldiny and T. Noël, in proceedings of the ***IEEE International Conference on Wireless and Mobile Computing, Networking and Communications (WiMob)***, Limassol Cyprus, October 2018 (acceptance rate: 28%)
- [**Indoor Deployment of Low-Power Wide Area Networks (LPWAN): a LoRaWAN case study**](http://dx.doi.org/10.1109/WiMOB.2016.7763213), P. Neumann, J. Montavont and T. Noël, in proceedings of the ***IEEE International Conference on Wireless and Mobile Computing, Networking and Communications (WiMob)***, New York USA, October 2016 (acceptance rate: 26.8%)
- [**RPL Border Router Redundancy in the Internet of Things**](http://dx.doi.org/10.1007/978-3-319-40509-4_14), Q-D. Nguyen, J. Montavont, N. Montavont and T. Noël, in proceedings of the ***International Conference on Ad-Hoc Networks and Wireless (AdHoc-Now)***, Lille France, July 2016 (acceptance rate: 37%)
- [**Integrating Mobility in RPL**](http://dx.doi.org/10.1007/978-3-319-15582-1_9), C. Cobârzan, J. Montavont and T. Noël, in proceedings of the ***European Conference on Wireless Sensor Networks (EWSN)***, Porto Portugal, February 2015 (acceptance rate: 21.5%)
- [**Theoretical Analysis of IPv6 Stateless Address Autoconfiguration in Low-power and Lossy Wireless Networks**](http://dx.doi.org/10.1109/RIVF.2015.7049899), J. Montavont, C. Cobârzan and T. Noël, in proceedings of the ***IEEE RIVF International Conference on Computing and Communication Technologies (RIVF)***, Cantho Vietnam, January 2015 (acceptance rate: 42%)
- [**Analysis and Performance Evaluation of RPL under Mobility**](http://dx.doi.org/10.1109/ISCC.2014.6912471), C. Cobârzan, J. Montavont and T. Noël, in proceedings of the ***IEEE Symposium on Computers and Communications (ISCC)***, Madeira Portugal, June 2014 (acceptance rate: 46.4%)
- [**Performance Evaluation of Mobile IPv6 Over 6LoWPAN**](http://dx.doi.org/10.1145/2387027.2387041), D. Roth, J. Montavont and T. Noël, in proceedings of the ***ACM International Symposium on Performance Evaluation of Wireless Ad Hoc, Sensor, and Ubiquitous Networks (PEWASUN)***, Paphos Cyprus Island, October 2012 (acceptance rate: 17%)
- [**Overhearing for Congestion Avoidance in Wireless Sensor Networks**](http://dx.doi.org/10.1007/978-3-642-22450-8_10), D. Roth, J. Montavont and T. Noël, in proceedings of the ***International Conference on Ad Hoc and Wireless (ADHOC-NOW)***, Paderborn Germany, July 2011 (acceptance rate 42%)
- [**LIFT: Layer Independent Fault Tolerance Mechanism for Wireless Sensor Networks**](http://dx.doi.org/10.1109/VETECS.2011.5956762), J. Beaudaux, A. Gallais, J. Montavont and T. Noël, in proceedings of the ***IEEE Vehicular Technology Conference (VTC-Spring)***, Budapest Hungary, May 2011 (acceptance rate 51%)
- [**MOBINET: Mobility Management Across Different Wireless Sensor Networks**](http://dx.doi.org/10.1109/WCNC.2011.5779156), D. Roth, J. Montavont and T. Noël, in proceedings of the ***IEEE Wireless Communications and Networking Conference (WCNC)***, Cancun Mexico, March 2011 (acceptance rate: 48%)
- [**Multiple Mobile Routers in NEMO: How Neighbor Discovery Can Assist Default Router Selection**](http://dx.doi.org/10.1109/PIMRC.2008.4699613), R. Kuntz, J. Montavont and T. Noël, in proceedings of the ***IEEE International Symposium on Personal Indoor and Mobile Radio Communications (PIMRC)***, Cannes France, September 2008
- [**Analysis of Mobile IPv6 Handover Optimizations and their Impact on Real-Time Communication**](http://dx.doi.org/10.1109/WCNC.2007.598), J. Montavont, E. Ivov and T. Noël, in proceedings of the ***IEEE Wireless Communications and Networking Conference (WCNC)***, Hong Kong China, March 2007 (acceptance rate: 47%)
- [**Wireless IPv6 Simulator: SimulX**](http://dl.acm.org/citation.cfm?id=1404595.1404634), N. Montavont, J. Montavont and S. Hachana, in proceedings of the ***ACM/SIGSIM Communications and Networking Simulation Symposium (CNS), located with Spring Simulation Multiconference (SpringSim)***, Norfolk USA, March 2007
- [**Deploying NEMO: A Practical Approach**](http://dx.doi.org/10.1109/ITST.2006.288768), J. Montavont, J. Lorchat and T. Noël, in proceedings of the ***International Conference on ITS Telecommunications (ITST)***, Chengdu China, June 2006
- [**IEEE 802.11 Handovers Assisted by GPS Information**](http://dx.doi.org/10.1109/WIMOB.2006.1696358), J. Montavont and T. Noël, in proceedings of the ***IEEE International Conference on Wireless and Mobile Computing, Networking and Communications (WiMob)***, Montréal Canada, June 2006
- [**Enhanced schemes for L2 handover in IEEE 802.11 networks and their evaluations**](http://dx.doi.org/10.1109/PIMRC.2005.1651681), J. Montavont, N. Montavont and T. Noël, in proceedings of the ***IEEE International Symposium on Personal Indoor and Mobile Radio Communications (PIMRC)***, Berlin Germany, September 2005 

### Refereed National Conferences (4)

- [**Selecting Parents with Wake-Up Radios for Load Balancing in RPL**](https://hal.archives-ouvertes.fr/hal-02124314), S. Sampayo, J. Montavont et T. Noël, dans les actes du ***colloque francophone sur la conception de protocoles, l’évaluation de performance et l’expérimentation des réseaux de communication (CoRes)***, Saint Laurent de la Cabrerisse, France, Juin 2019
- **De l'Internet mobile à la mobilité dans l'Internet des objets**, J. Montavont, A. Gallais et T. Noël, article invité dans les actes des *journées francophones Mobilité et Ubiquité (Ubimob)*, Anglet France, June 2012
- [**MOBINET : Gestion de la Mobilite a travers differents Reseaux de Capteurs Sans Fil**](http://hal.inria.fr/inria-00475581), D. Roth, J. Montavont and T. Noël, dans les actes des ***Rencontres Francophones sur les Aspects Algorithmiques de Telecommunications (Algotel)***, Cote d'Opale France, June 2010 (acceptance rate 57%)
- [**Anticipation des Handovers des Noeuds IPv6 a l'aide d'information de Geolocalisation**](http://hal.inria.fr/inria-00110275), J. Montavont, T. Noël et K. Guillouard, dans les actes du ***Colloque Francophone sur l'Ingenierie des Protocoles (CFIP)***, Tozeur Tunisia, November 2006

### Workshops (3)

- [**A Performance Study of the Behavior of the Wake-Up Radio in Real-World Noisy Environments**](https://www.ewsn.org/file-repository/ewsn2020/206_211_sampayo.pdf), S. Sampayo, J. Montavont and T. Noël, in proceedings of the ***Workshop on Wake-Up radio technologies for next generation wireless communications (AWAKE), in conjunction with EWSN 2020***, Lyon France, February 2020
- [**Implementation of an IPv6 Stack for NS-3**](http://dx.doi.org/10.4108/ICST.VALUETOOLS2008.4374), S. Vincent, J. Montavont, N. Montavont, in proceedings of the ***International Workshop on NS-2 (WNS2), in conjunction with the 3rd International Conference on Performance Evaluation Methodologies and Tools (VALUETOOLS)***, Athens Greece, October 2008
- [**Advantages of Flow Bindings: an Embedded Mobile Network Use Case**](http://dl.acm.org/citation.cfm?id=1390576.1390593), A. Boutet, B. Le Texier, J. Montavont, N. Montavont, G. Schreiner, in proceedings of the ***Workshop on Experimental Evaluation and Deployment Experiences on Vehicular Networks (WEEDEV)***, in conjunction with TRIDENTCOM, Innsbruck Austria, March 2008

### Demonstrations

- [**CASINO: Creating Alea with a Sensor-based Interactive Network**](http://dx.doi.org/10.1145/1869983.1870033), J. Beaudaux, A. Gallais, R. Kuntz, J. Montavont, T. Noël, D. Roth, F. Theoleyre and E. Valentin, demonstration abstract in proceedings of the ***ACM Conference on Embedded Networked Sensor Systems (SenSys)***, Zurich Switzerland, November 2010
    
