---
title: ""
output:
  html_document:
    toc: False
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### PhD Students

- **Florent Hardy** (2025 - ...)  
Co-supervision with Jean-Romain Luttringer and Pascal Mérindol  
Ph.D. Thesis: *Towards Eco-Efficient Autonomous Networks: Deep Programmability and Energy-Aware Routing Protocols*   
Funding: ANR JCJC Garden

- **Anjali Shaw** (2025 - ...)  
Co-supervision with Thomas Bégin (LIP, Lyon) and Isabelle Guérin-Lassous (LIP, Lyon)   
Ph.D. Thesis: *Multi-RAT and Multi-UPF Resource Allocation for Ultra-Reliable Low-Latency Communications in 5G and Beyond*  
Funding: Future Networks Priority Research Programme and Equipment (PEPR), DONUTS project

- **Ali Mustapha** (2024 - ...)   
Co-supervision with Fabrice Théoleyre    
Ph.D. Thesis: *Inter-domain Monitoring and Predictions for Service Orchestration in 5G*   
Funding: Future Networks Priority Research Programme and Equipment (PEPR), NF-MUST project

- **Thomas Le Tarnec** (2024 - ...)   
Co-supervision with Georgios Papadopoulos (IRISA), Guillaume Le Gall (IRISA) and Thomas Noël  
Ph.D. Thesis: *Programmable Wireless Protocol Stack*   
Funding: PERENNE ANR research project

- **Ahmad Mahmod** (2023 - ...)   
Co-supervision with Thomas Noël   
Ph.D. Thesis: *Software Defined Low-Power and Lossy Wireless Networks*  
Funding: MESR grant

- <details style="margin-bottom: 20px;"><summary><strong>Former PhD Students</strong></summary>
  - **Amaury Bruniaux** (2020 - 2024)  
Co-supervision with Nicolas Montavont, Georgios Papadopoulos and Thomas Noël  
Ph.D. Thesis: SDN approach to support ubiquitous IoT technologies   
*PhD work discontinued before defense*

  - **Farzad Veisi** (2020 - 2023)  
Co-supervision with Fabrice Théoleyre  
Ph.D. Thesis: [Enhancing industrial Internet of things through software-defined networking: from building the network to flow management](https://theses.fr/2023STRAD061)  
Funding: MESR grant

  - **Sebastian Lucas Sampayo** (2018 - 2021)  
Co-supervision with Thomas Noël  
Ph.D. Thesis: [Polymorphic network protocol suite in heterogeneous wake-up IoT networks](https://theses.fr/2021STRAD005)  
Funding: ANR Infra - WakeUP project

  - **Cosmin Cobârzan** (2012 - 2015)  
Co-supervision with Thomas Noël  
Ph.D. Thesis: [Internet of Highly Mobile Things](https://theses.fr/2015STRAD037)  
Funding: grant from Institut Mines-Telecom - Future et Rupture program

  - **Damien Roth** (2009 - 2012)  
Co-supervision with Thomas Noël  
Ph.D. Thesis: [Mobility management of wireless sensor networks](https://theses.fr/2012STRAD031)  
Funding: MESR grant

  - **Romain Kuntz** (2007 - 2010)  
Co-supervision with Thomas Noël  
Ph.D. Thesis: [Medium access control facing the dynamics of wireless sensor networks](https://theses.fr/2010STRA6077)
</details>

### Master 2 Internship

- **Céleste Kerlogot** (2026)  
Co-supervision with Jean-Romain Luttringer  
Thesis: *Study of Gray-Failure in Computer Networks: Taxonomy and Data Generation*   
Funding: ANR TURFU-NET research project

- <details style="margin-bottom: 20px;"><summary><strong>Former Master Students</strong></summary>
  - **Florent Hardy** (2025)  
Co-supervision with Jean-Romain Luttringer  
Thesis: *Profiling and Optimization of Energy Consumption in Programmable Networks*  
Funding: ANR JCJC GARDEN

  - **Anna Beatriz De-Souza-Perotto** (2024)  
Co-supervision with Thomas Noël  
Thesis: *Establishing a 5G-Enabled Connected Operating Room and Hospital-to-Home Patient Monitoring: Optimization of Latency and Handovers between Private and Public 5G Networks*  
Funding: ITI Healthtech grant

  - **Simon Raul** (2022)  
Co-supervision with Cristel Pelsser and Thomas Noël  
Thesis: *Anomaly detection in Internet of Things*  
Funding: Cisco Research project

  - **Brandon Foubert** (2018)  
Thesis: *Cooperation between multiple RPL networks*  
Funding: Grant from University

  - **Pierre Neumann** (2016)  
Thesis: *Heterogeneous Internet of Things*  
Funding: LoRa CROFT project

  - **Quang Duy Nguyen** (2015)  
Thesis: *Multihoming in the Internet of Things*  
Funding: scholarship grant from IDEX Mobility Program - Master Internship of University of Strasbourg